FROM symbios/container
COPY . /go/src/github.com/dnascimento/GoHttpsMutualAuth/http-server
RUN go build github.com/dnascimento/GoHttpsMutualAuth/http-server
RUN go install github.com/dnascimento/GoHttpsMutualAuth/http-server