FROM symbios/container
COPY . /go/src/github.com/dnascimento/GoHttpsMutualAuth/http-client
RUN go build github.com/dnascimento/GoHttpsMutualAuth/http-client
RUN go install github.com/dnascimento/GoHttpsMutualAuth/http-client